"""Generated artefacts and version numbers must not drift.

The catalog is the single source of truth for what the tool checks. If the
prose a model reads, or the sample a user judges the tool by, disagrees with
it, the documentation is actively misleading.
"""

from __future__ import annotations

import json
import re
import subprocess
import sys
import tomllib
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parent.parent


def test_patterns_reference_is_regenerated(plugin_root):
    proc = subprocess.run(
        [sys.executable, str(plugin_root / "scripts" / "gen_catalog_docs.py"), "--check"],
        capture_output=True, text=True)
    assert proc.returncode == 0, (
        proc.stdout + proc.stderr +
        "\nRun: uv run scripts/gen_catalog_docs.py")


def test_sample_report_covers_every_scanned_pattern(catalog):
    sample = (ROOT / "examples" / "sample-report.md").read_text()
    missing = [p["id"] for p in catalog["patterns"] if f"`{p['id']}`" not in sample]
    assert not missing, (
        f"sample-report.md does not mention {missing} — regenerate it with "
        f"uv run scripts/gen_sample_report.py")


def test_sample_report_is_a_real_artefact(catalog):
    """It must be produced by the pipeline, not written by hand."""
    sample = (ROOT / "examples" / "sample-report.md").read_text()
    assert "Generated by scripts/gen_sample_report.py" in sample
    assert "thunderstruck.report/v1" in sample
    # Evidence refs of all three kinds appear, so the sample demonstrates the
    # contract rather than just asserting it.
    assert "_code_" in sample and "_commit_" in sample and "_detector_" in sample


def test_sample_report_shows_the_injection_finding():
    """The prompt-injection fracture is the one a reader most needs to see
    handled, because it is the one that tests the tool's own integrity."""
    sample = (ROOT / "examples" / "sample-report.md").read_text()
    assert "`OTHER`" in sample
    assert "automated" in sample.lower() and "comment" in sample.lower()


def test_catalog_tiers_match_the_documented_split(catalog):
    tier_a = [p["id"] for p in catalog["patterns"] if p["tier"] == "A"]
    tier_b = [p["id"] for p in catalog["patterns"] if p["tier"] == "B"]
    assert tier_a == [f"S{n:02d}" for n in (*range(1, 11), 27, 28, 29)], tier_a
    assert tier_b == [f"S{n:02d}" for n in range(11, 20)], tier_b


def test_sample_report_links_its_refs():
    """Every resolved file:line, detector and commit ref in the sample is one
    click from the code. Shape only — this does not prove the sample is fresh."""
    sample = (ROOT / "examples" / "sample-report.md").read_text()
    link = r"\[`[^`]+`\]\(https://github\.example\.com/acme/fixture/"
    refs = [line for line in sample.splitlines()
            if re.match(r"- _(code|detector|commit)_ ", line)]
    locations = [line for line in sample.splitlines()
                 if re.match(r"\*\*(high|medium|low) confidence\*\* · ", line)]
    assert refs and locations
    unlinked = [line for line in refs if not re.match(r"- _\w+_ " + link, line)]
    unlinked += [line for line in locations if not re.search(r"\*\* · " + link, line)]
    assert not unlinked, "unlinked refs in sample-report.md:\n" + "\n".join(unlinked)


def test_versions_agree():
    plugin = json.loads((ROOT / ".claude-plugin" / "plugin.json").read_text())
    market = json.loads((ROOT / ".claude-plugin" / "marketplace.json").read_text())
    with (ROOT / "pyproject.toml").open("rb") as fh:
        pyproject = tomllib.load(fh)

    entry = next(p for p in market["plugins"] if p["name"] == "thunderstruck")
    versions = {
        "plugin.json": plugin["version"],
        "marketplace.json": entry["version"],
        "pyproject.toml": pyproject["project"]["version"],
    }
    assert len(set(versions.values())) == 1, f"version drift: {versions}"

    changelog = (ROOT / "CHANGELOG.md").read_text()
    match = re.search(r"^##\s*\[?(\d+\.\d+\.\d+)\]?", changelog, re.M)
    assert match, "CHANGELOG.md has no version heading"
    assert match.group(1) == plugin["version"], (
        f"CHANGELOG top entry {match.group(1)} != plugin version {plugin['version']}")


def test_example_profile_parses_and_uses_real_pattern_ids(catalog):
    path = ROOT / "examples" / "thunderstruck.toml.example"
    with path.open("rb") as fh:
        profile = tomllib.load(fh)
    known = {p["id"] for p in catalog["patterns"]}
    for pid in (profile.get("patterns") or {}):
        assert pid in known, f"{path.name} references unknown pattern {pid}"
    for pid, override in (profile.get("patterns") or {}).items():
        if isinstance(override, dict) and "tier" in override:
            assert str(override["tier"]).upper() in {"A", "B", "C"}


def test_readme_documents_the_privacy_position():
    readme = (ROOT / "README.md").read_text().lower()
    assert "privacy" in readme
    for claim in ("network", "local"):
        assert claim in readme, f"README does not address {claim!r}"


def test_every_script_has_a_docstring():
    for script in sorted((ROOT / "scripts").glob("*.py")):
        text = script.read_text()
        body = text.split('"""')
        assert len(body) >= 3, f"{script.name} has no module docstring"


def test_manifest_does_not_redeclare_autodiscovered_hooks():
    """`hooks/hooks.json` is auto-discovered, and the manifest's `hooks` field
    MERGES with it rather than replacing it. Naming it there loads the same
    file twice and the plugin fails to load at runtime — which
    `claude plugin validate` does not catch, only `claude plugin list` does.
    """
    manifest = json.loads((ROOT / ".claude-plugin" / "plugin.json").read_text())
    assert (ROOT / "hooks" / "hooks.json").is_file()
    assert "hooks" not in manifest, (
        "plugin.json declares `hooks` while hooks/hooks.json also exists; the "
        "runtime rejects this as a duplicate hooks file")


def test_manifest_does_not_redeclare_other_autodiscovered_dirs():
    manifest = json.loads((ROOT / ".claude-plugin" / "plugin.json").read_text())
    for field, default_dir in (("skills", "skills"), ("agents", "agents")):
        if (ROOT / default_dir).is_dir():
            assert field not in manifest, (
                f"plugin.json declares `{field}` while {default_dir}/ exists; "
                f"rely on auto-discovery instead")


def test_sample_report_shows_service_context():
    sample = (ROOT / "examples" / "sample-report.md").read_text()
    assert "## Service context" in sample
    assert "_catalog_ `dependencyOf component:default/web-frontend`" in sample
    assert "| Dependents / dependencies |" in sample
    assert "real file:line, commit, detector hit or catalog edge" in sample
    assert "a detector hit or a catalog edge" in sample.split("-->")[0]
    assert "ignore previous instructions" not in sample


def test_service_context_is_wired_into_the_prompts():
    config = (ROOT / "skills" / "thunderstruck-context-config" / "SKILL.md").read_text()
    assert config.startswith("---\nname: thunderstruck-context-config\n")
    assert "--approve" in config and "enabled = false" in config
    assert "context.py\" --show" in config and "--expect" in config
    scan = (ROOT / "skills" / "thunderstruck-scan" / "SKILL.md").read_text()
    assert "context.py" in scan and "thunderstruck-context-config" in scan
    agent = (ROOT / "agents" / "thunderstruck-investigator.md").read_text()
    assert "Service context" in agent and "`catalog`" in agent
    plugin = json.loads((ROOT / ".claude-plugin" / "plugin.json").read_text())
    assert "skills" not in plugin


def test_docs_state_what_the_context_command_receives():
    readme = (ROOT / "README.md").read_text()
    orch = (ROOT / "skills" / "thunderstruck-scan" / "references"
            / "orchestration.md").read_text()
    for doc in (readme, orch):
        flat = " ".join(doc.split())
        assert "only the entity ref" not in flat and "nothing but the entity ref" not in flat
        assert "each neighbour's ref" in flat and "environment" in flat


def test_ci_trust_override_is_documented():
    readme = (ROOT / "README.md").read_text()
    config = (ROOT / "skills" / "thunderstruck-context-config" / "SKILL.md").read_text()
    service = readme.split("### Service context")[1].split("\n## ")[0]
    for doc in (service, config):
        assert "THUNDERSTRUCK_TRUST_CONTEXT=1" in doc and "CI" in doc
